eureka:
  client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.44:3306/sell?characterEncoding=utf-8&useSSL=false
env:
   test
